# Generated by Django 3.1.3 on 2020-12-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('checked', models.BooleanField(default=False)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_exp', models.DateField()),
                ('list_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_app.list')),
            ],
        ),
    ]
